language: rust
rust:
  - nightly-2017-01-08
cache: cargo
before_script: (cargo install rustfmt || true)
script:
- |
  export PATH=$PATH:~/.cargo/bin &&
  rustfmt --write-mode=diff ./src/main.rs ./build.rs ./lib/*/src/lib.rs
